---
- name: "Recursive"
  become: true
  hosts: recursive
  vars_files:
    - "../vars/common.yaml"
    - "../vars/terraform.yaml"

  vars:
    root_zone: "."
    root_ns: "ns.root."

  tasks:
    - name: "Recursive : update"
      ansible.builtin.apt:
        update_cache: true

    - name: "Recursive : install"
      ansible.builtin.apt:
        state: present
        name:
          - bind9
          - bind9utils
          - dnsutils

    - name: "Recursive : stop service"
      ansible.builtin.systemd:
        name: bind9
        state: stopped

    - name: "Recursive : remove config dir"
      ansible.builtin.file:
        path: "{{ bind_path }}"
        state: absent

    - name: "Recursive : create config dir"
      ansible.builtin.file:
        path: "{{ bind_path }}"
        state: directory
        owner: root
        group: bind
        mode: '0755'

    - name: "Recursive : create named.conf"
      ansible.builtin.template:
        src: "templates/recursive/recursive.conf.j2"
        dest: "{{ bind_path }}/named.conf"
        owner: root
        group: bind
        mode: '0644'

    - name: "Recursive : create zones dir"
      ansible.builtin.file:
        path: "{{ zones_path }}"
        state: directory
        owner: bind
        group: bind
        mode: '0755'

    - name: "Recursive : create zones"
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: bind
        mode: '0644'
      loop:
        - { src: "templates/common/db.root.hints.j2", dest: "{{ zones_path }}/db.root.hints" }
        - { src: "templates/common/db.local.j2", dest: "{{ zones_path }}/db.local" }
        - { src: "templates/common/db.0.j2", dest: "{{ zones_path }}/db.0" }
        - { src: "templates/common/db.127.j2", dest: "{{ zones_path }}/db.127" }
        - { src: "templates/common/db.255.j2", dest: "{{ zones_path }}/db.255" }

    - name: "Recursive : check named.conf"
      ansible.builtin.command:
        cmd: "named-checkconf {{ bind_path }}/named.conf"
      register: conf_status
      failed_when: conf_status.rc != 0
      changed_when: false

    - name: "Recursive : reload and restart service"
      ansible.builtin.systemd:
        name: bind9
        state: restarted
        enabled: true
        daemon_reload: true
