---
- name: "RECR"
  become: true
  hosts: recr
  vars_files:
    - "../variables/res-recr.yaml"
    - "../variables/common.yaml"
    - "../variables/terraform.yaml"

  tasks:
    - name: "RECR : update"
      ansible.builtin.apt:
        update_cache: true

    - name: "RECR : install"
      ansible.builtin.apt:
        state: present
        name:
          - bind9
          - bind9utils
          - dnsutils

    - name: "RECR : stop service"
      ansible.builtin.systemd:
        name: bind9
        state: stopped

    - name: "RECR : remove dir : {{ bind_path }}"
      ansible.builtin.file:
        path: "{{ bind_path }}"
        state: absent

    - name: "RECR : create dir : {{ bind_path }}"
      ansible.builtin.file:
        path: "{{ bind_path }}"
        state: directory
        owner: root
        group: bind
        mode: '0755'

    - name: "RECR : create named.conf"
      ansible.builtin.template:
        src: "{{ templates_path }}/recursive/recr.conf.j2"
        dest: "{{ bind_path }}/named.conf"
        owner: root
        group: bind
        mode: '0644'

    - name: "RECR : create dir : {{ zone_path }}"
      ansible.builtin.file:
        path: "{{ zone_path }}"
        state: directory
        owner: bind
        group: bind
        mode: '0755'

    - name: "RECR : create zones"
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: bind
        mode: '0644'
      loop:
        - { src: "{{ templates_path }}/common/db.root.hints.j2", dest: "{{ zone_path }}/db.root.hints" }
        - { src: "{{ templates_path }}/common/db.local.j2", dest: "{{ zone_path }}/db.local" }
        - { src: "{{ templates_path }}/common/db.0.j2", dest: "{{ zone_path }}/db.0" }
        - { src: "{{ templates_path }}/common/db.127.j2", dest: "{{ zone_path }}/db.127" }
        - { src: "{{ templates_path }}/common/db.255.j2", dest: "{{ zone_path }}/db.255" }

    - name: "RECR : check named.conf"
      ansible.builtin.command:
        cmd: "named-checkconf {{ bind_path }}/named.conf"
      register: conf_status
      failed_when: conf_status.rc != 0
      changed_when: false

    - name: "RECR : create dir : {{ bind_logs_path }}"
      ansible.builtin.file:
        path: "{{ bind_logs_path }}"
        state: directory
        owner: root
        group: bind
        mode: '0755'

    - name: "RECR : create file : {{ bind_logs_file }}"
      ansible.builtin.file:
        path: "{{ bind_logs_path }}/{{ bind_logs_file }}"
        state: touch
        owner: bind
        group: bind
        mode: '0644'

    - name: "RECR : reload and restart service"
      ansible.builtin.systemd:
        name: bind9
        state: restarted
        enabled: true
        daemon_reload: true
